name: Build Eleventy and deploy to Dreamhost (Staging)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v2

      - name: 1️⃣1️⃣ Eleventy Build
        uses: mfyz/actions-eleventy@master

      - name: 🧑🏻‍💻 Deploy to Dreamhost (Staging)
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: staging.ronnie.fyi
          username: ${{ secrets.ftp_username_staging }}
          password: ${{ secrets.ftp_password_staging }}
          server-dir: /staging.ronnie.fyi/
          port: 22
