image: node:lts
name: Build Eleventy and deploy to Dreamhost (Staging)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "node -v"

      - name: 🚚 Get Latest Code
        uses: actions/checkout@v2

      - name: 1️⃣1️⃣ Eleventy Build
        uses: mfyz/actions-eleventy@master

      - name: 🧑🏻‍💻 Deploy to Dreamhost (Staging)
        uses: AbleLincoln/push-to-sftp@v1.0
        with:
          host: ronnie.fyi
          port: 22
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          sourceDir: ./_site/
          targetDir: ./ronnie.fyi/
