name: Build Eleventy and deploy to Dreamhost (Staging)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Eleventy
        uses: TartanLlama/actions-eleventy@v1.1
