name: Build Eleventy and deploy to Dreamhost (Staging)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: 1️⃣1️⃣ Eleventy Build
        # uses: mfyz/actions-eleventy@master
        run: npm install
        run: npx 11ty/eleventy

      - name: 🧑🏻‍💻 Deploy to Dreamhost (Staging)
        uses: AbleLincoln/push-to-sftp@v1.0
        with:
          host: ronnie.fyi
          port: 22
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          sourceDir: ./_site/
          targetDir: ./ronnie.fyi/
