name: Build Eleventy and deploy to Dreamhost (Staging)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      strategy:
        matrix:
          node-version: [12.x]

      - name: 🚚 Get Latest Code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 1️⃣1️⃣ Eleventy Build
        uses: mfyz/actions-eleventy@master

      - name: 🧑🏻‍💻 Deploy to Dreamhost (Staging)
        uses: AbleLincoln/push-to-sftp@v1.0
        with:
          host: ronnie.fyi
          port: 22
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          sourceDir: ./_site/
          targetDir: ./ronnie.fyi/
